# Generated by Django 2.1.2 on 2018-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_date', models.DateField()),
                ('field_text', models.CharField(max_length=100)),
            ],
        ),
    ]
